#!/bin/bash

# https://gist.github.com/crolopez/cda6757d96e9013a6fbe91685c059a69
# Script to deploy Java applications in serverless mode
# Based on the one generated by io.quarkus:quarkus-amazon-lambda dependency
# Version 3

function cmd_create() {
  echo Creating function
  set -x
  aws lambda create-function \
    --function-name ${FUNCTION_NAME} \
    --zip-file ${ZIP_FILE} \
    --handler ${HANDLER} \
    --runtime ${RUNTIME} \
    --role ${LAMBDA_ROLE_ARN} \
    --timeout 15 \
    --memory-size 256 \
    $LAMBDA_META > /dev/null
}

function cmd_delete() {
  echo Deleting function
  set -x
  aws lambda delete-function --function-name ${FUNCTION_NAME}
}

function cmd_invoke() {
  echo Invoking function

  inputFormat=""
  if [ $(aws --version | awk '{print substr($1,9)}' | cut -c1-1) -ge 2 ]; then inputFormat="--cli-binary-format raw-in-base64-out"; fi

  set -x

  aws lambda invoke response.txt \
    ${inputFormat} \
    --function-name ${FUNCTION_NAME} \
    --payload file://payload.json \
    --log-type Tail \
    --query 'LogResult' \
    --output text |  base64 --decode
  { set +x; } 2>/dev/null
  cat response.txt && rm -f response.txt
}

function cmd_update_env_vars() {
  echo Updating environment variables
  set -x
  eval "aws lambda update-function-configuration \
    --function-name ${FUNCTION_NAME} \
    $LAMBDA_META > /dev/null"
}

function cmd_update() {
  cmd_update_env_vars

  echo Updating function
  set -x
  aws lambda update-function-code \
    --function-name ${FUNCTION_NAME} \
    --zip-file ${ZIP_FILE} > /dev/null
}

function cmd_deploy() {
  echo Checking if the $FUNCTION_NAME function exists...

  aws lambda get-function --function-name $FUNCTION_NAME > /dev/null 2>&1
  if [ $? -eq 0 ] 
  then
    cmd_update 
  else
    cmd_create
  fi
}

function usage() {
  [ "_$1" == "_" ] && echo -e "\nUsage (JVM): \n$0 [create|delete|invoke|deploy] [function_name] [ENV1=val1,ENV2=val2...]\ne.g.: $0 invoke HelloWorld QUARKUS_LAMBDA_HANDLER=hello-world"
  [ "_$1" == "_" ] && echo -e "\nUsage (Native): \n$0 native [create|delete|invoke|deploy] [function_name] [ENV1=val1,ENV2=val2...]\ne.g.: $0 native invoke HelloWorld QUARKUS_LAMBDA_HANDLER=hello-world"

  [ "_" == "_`which aws 2>/dev/null`" ] && echo -e "\naws CLI not installed. Please see https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html"
  [ ! -e $HOME/.aws/credentials ] && [ "_$AWS_ACCESS_KEY_ID" == "_" ] && echo -e "\naws configure not setup.  Please execute: aws configure"
  [ "_$LAMBDA_ROLE_ARN" == "_" ] && echo -e "\nEnvironment variable must be set: LAMBDA_ROLE_ARN\ne.g.: export LAMBDA_ROLE_ARN=arn:aws:iam::123456789012:role/my-example-role"
}

if [ "_$1" == "_" ] || [ "$1" == "help" ]
 then
  usage
fi

if [ "$1" == "native" ]
then
  shift
  RUNTIME=provided
  FUNCTION_NAME="${2}Native"
  LAMBDA_META="--environment Variables='{DISABLE_SIGNAL_HANDLERS=true,$3}'"
else
  RUNTIME=java11
  FUNCTION_NAME=$2
  LAMBDA_META="--environment Variables='{$3}'"
fi

HANDLER=io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
  ZIP_FILE="fileb://${PWD}/build/function.zip"

eval cmd_${1}
{ set +x; } 2>/dev/null