quarkus:
  lambda:
    handler: telegram-handler

telegram:
  api:
    hostname: api.telegram.org
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

bookingPlatform:
  hostname: ${BOOKING_HOSTNAME}
  login:
    user: ${BOOKING_LOGIN_USER}
    password: ${BOOKING_LOGIN_PASSWORD}
  matching-tag:
    office: ${BOOKING_MATCHING_TAG_OFFICE}
    parking: ${BOOKING_MATCHING_TAG_PARKING}
  keys:
    office:
      bc: ${BOOKING_KEYS_OFFICE_BC}
      l: ${BOOKING_KEYS_OFFICE_L}
    parking:
      bc: ${BOOKING_KEYS_PARKING_BC}
      l: ${BOOKING_KEYS_PARKING_L}