quarkus:
  lambda:
    handler: telegram-handler

telegram:
  api:
    hostname: api.telegram.org
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    default-reporting-channel: ${TELEGRAM_DEFAULT_REPORTING_CHANNEL}
bookingPlatform:
  hostname: ${BOOKING_HOSTNAME}
  login:
    user: ${BOOKING_LOGIN_USER}
    password: ${BOOKING_LOGIN_PASSWORD}
  matching-tag:
    office: ${BOOKING_MATCHING_TAG_OFFICE}
    parking: ${BOOKING_MATCHING_TAG_PARKING}
  schedule:
      parking:
        offset: "2w"
  booking-behaviour:
    max-parallel-bookings: 4
    book-timeout: 5
  booking-preferences:
    - space: ${BOOKING_PREFERENCES_0_SPACE}
      priority:
        - ${BOOKING_PREFERENCES_0_PRIORITY_0}
        - ${BOOKING_PREFERENCES_0_PRIORITY_1}
        - ${BOOKING_PREFERENCES_0_PRIORITY_2}
    - space: ${BOOKING_PREFERENCES_1_SPACE}
      priority:
        - ${BOOKING_PREFERENCES_1_PRIORITY_0}
    - space: ${BOOKING_PREFERENCES_2_SPACE}
      priority:
        - ${BOOKING_PREFERENCES_2_PRIORITY_0}
        - ${BOOKING_PREFERENCES_2_PRIORITY_1}
  keys:
    office:
      bc: ${BOOKING_KEYS_OFFICE_BC}
      l: ${BOOKING_KEYS_OFFICE_L}
    parking:
      bc: ${BOOKING_KEYS_PARKING_BC}
      l: ${BOOKING_KEYS_PARKING_L}